#include<stdio.h>
char k;

int main()
{



FILE *file=fopen("Data Structure.c","r");
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
 k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);
k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);k=fgetc(file);
printf("%c",k);
fclose(file);
	

return 0;}


